# This script recieves questions, and generates answers #
# use simple GPT method for MVP 

# import packages
import openai

# function for generation the answer to questions based on the question
def answerGen(question):
    """This function generates the answer to a proposed question
    Args: question - [string] question recieved from Speech Processing Module
    Returns: response - [string] response to question generated by a GPT model
    """

    # define the API key
    openai.api_key = "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"
    # create query
    query = f"Answer the following questions in a short paragraph in the style of an interesting lecturer: {question}"
    # create completion
    completions = openai.Completion.create(
            engine="text-davinci-003",
            prompt=query,
            max_tokens=1024,
            n=1, # generate a single completion
            temperature=0.2, # keeps responses narrow
        )
    # retrieve answer
    response = completions.choices[0]["text"]
    # returns answer
    return response