version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roboserver
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: roboserver
      MYSQL_HOST: db
    depends_on:
      - db
