# This script recieves questions, and generates answers #
# use simple GPT method for MVP 

# import packages
from chat import chat_model

# function for generation the answer to questions based on the question
def answerGen(question):
    """This function generates the answer to a proposed question
    Args: question - [string] question recieved from Speech Processing Module
    Returns: response - [string] response to question generated by a GPT model
    """

    query = f"Answer the following questions in a short paragraph in the style of an interesting lecturer: {question}"

    # get response to query using selelcted model
    response = chat_model.getResponse(query)
    
    return response
